[package]
name = "lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
loom = { path = "../core", package = "loom" }

# 日志
log = "0.4.29"
simple_logger = "5.1.0"

# LSP 协议
lsp-server = "0.7.9"
lsp-types = "0.97.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
